### ISSUE TITLE
'Object reference not set to an instance of an object' error when trying to compile environment from Clio Explorer

### ISSUE THREAD

**Issue by josehernaC2C** [Advance-Technologies-Foundation/clio-docs#1]
Getting 'System.NullReferenceException: Object reference not set to an instance of an object.' when trying almost any command on clio explorer. Attached is a screen shot of the error and the environment configuration. 

Any ideas what I might be missing?

Thanks,
Jose

![clio explorer error](https://user-images.githubusercontent.com/132952532/236937324-f92158f8-429f-4e54-b1f1-202742a8633f.png)

**Comment by vladimir-nikonov** [comment]
not reproduced
