### ISSUE TITLE
Error when I try to add clio workspase

### ISSUE THREAD

**Issue by AlekseyNigreskul** [Advance-Technologies-Foundation/clio-docs#2]
Hi! I try to add clio workspase and I get the error 
![Снимок экрана 2023-07-12 162531](https://github.com/Advance-Technologies-Foundation/clio-docs/assets/36301305/61112bdc-8fa9-4652-b74b-13aab123b5a2)
But folder is created

**Comment by vladimir-nikonov** [comment]
@AlekseyNigreskul  hi, please check that you install clio after installing clio explorer
<img width="459" alt="image" src="https://github.com/Advance-Technologies-Foundation/clio-docs/assets/26967647/bcf0b2d8-59e2-408d-b75b-3218544c963a">
or use command
`dotnet tool install clio -g`
