### ISSUE TITLE
Cannot access the connection

### ISSUE THREAD

**Issue by Geev108** [Advance-Technologies-Foundation/clio-docs#3]
Even though I added a new connection, I cannot see the connection in the Clio Explorer.
![image](https://github.com/Advance-Technologies-Foundation/clio-docs/assets/97938880/45082a49-3de6-4e9d-b691-d23d2e2d4343)

**Comment by vladimir-nikonov** [comment]
update please clio version to 6.0.2.17
<img width="451" alt="image" src="https://github.com/Advance-Technologies-Foundation/clio-docs/assets/26967647/57b629c0-9b25-4144-a7fd-a6dbe87ab4c4">
